all:
	cd Database; make
	cd DataTypes; make
	cd Gedcom; make
	cd Interp; make
	cd Parser; make
	cd Utils; make
	cd Validate; make
	cd Operations; make

clean:
	cd Database; make clean
	cd DataTypes; make clean
	cd Gedcom; make clean
	cd Interp; make clean
	cd Parser; make clean
	cd Utils; make clean
	cd Validate; make clean
	cd Operations; make clean
